version: '3'

services:
  poem:
    build:
      context: .
    restart: always
    working_dir:  /home/pwn
    container_name: poem
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9000:9000"
    entrypoint: /etc/init.sh
