version: "3"

services:
  app:
    build: ./app
    restart: always
    env_file: .env
  
  nginx:
    build: ./nginx
    volumes:
      - /etc/seccon/_.beginners.seccon.games.crt:/etc/nginx/certs/server.crt:ro
      - /etc/seccon/_.beginners.seccon.games.key:/etc/nginx/certs/server.key:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    restart: always
