version: '3'

services:
  no_control:
    build:
      context: .
    restart: always
    working_dir:  /home/pwn
    container_name: no_control_chall
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9005:9005"
    entrypoint: /etc/init.sh
