version: '3'

services:
  forgot_some_exploit:
    build:
      context: .
    restart: always
    working_dir:  /home/pwn
    container_name: forgot_some_exploit_chall
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9002:9002"
    entrypoint: /etc/init.sh
