version: '3'

services:
  rewriter2:
    build:
      context: .
    restart: always
    working_dir:  /home/pwn
    container_name: rewriter2
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9001:9001"
    entrypoint: /etc/init.sh
