version: '3'

services:
  yaro:
    build:
      context: .
    restart: always
    working_dir:  /home/misc
    container_name: yaro_chall
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "5003:5003"
    entrypoint: /etc/init.sh
